name: PR check
on: [push, pull_request]
jobs: 
  run: 
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        run: yarn install
      - name: Run tests and collect coverage
        run: yarn test
      - name:  Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}